name: RepoDispatch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  RepoDispatch:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ProtoByter/SchoolDigitalSignage
          event-type: SDSServiceUpdated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
